# Starter pipeline
- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'SN DEV DevOps Connection'
    upstream: 'Build'
    Phase: 'STARTED'
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'SN DEV DevOps Connection'
    upstream: 'Build'
    Phase: 'COMPLETED'
- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'SN DEV DevOps Connection'
    upstream: 'Test'
    Phase: 'STARTED'
- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'SN DEV DevOps Connection'
    upstream: 'Test'
    Phase: 'COMPLETED'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
